# Donation and development support

### If you wish to support development and bugfixing of this script or any others I work on please consider a donation

[![Donate via Paypal.me](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/djbp)
